namespace Plugins;

using System.ComponentModel;
using System.Net;
using System.Net.Mail;
using Microsoft.SemanticKernel;

public class EmailPlugin
{
    [KernelFunction, Description("generate the email template with the given message")]
    public static string EmailTemplate([Description("The message that needs to be used for sending email")]
     string message)
    {
        return "Email Template" + message;
    }

    [KernelFunction, Description("Sends the email with the given input email templated message")]
    public static string SendEmail([Description("The email templated message that will be used for sending email")]
     string message)
    {

        using (var client = new SmtpClient())
        {
            client.Host = "smtp.gmail.com";
            client.Port = 587;
            client.DeliveryMethod = SmtpDeliveryMethod.Network;
            client.UseDefaultCredentials = false;
            client.EnableSsl = true;
            client.Credentials = new NetworkCredential("GMAILCOM", "xfuygdsifyugdwfdshbfjhds");
            using (var mailMessage = new MailMessage(
                from: new MailAddress("xxxx", "AutoGenerated"),
                to: new MailAddress("xxx", "Sai Nitesh")
                ))
            {

                mailMessage.Subject = "SK Config";
                mailMessage.Body = ".......Semantic Kernel ---- "+ message;

                client.Send(mailMessage);
            }
        }

        return "Success:::Email  Sent  with  message ::" + message;
    }

}